### ISSUE TITLE
Pass in N_PROCESSES?

### ISSUE THREAD

**Issue by lilyminium** [mattwthompson/ib#3]
N_PROCESSES=14 is hardcoded here: https://github.com/mattwthompson/ib/blob/main/ibstore/_minimize.py#L16

Would it be possible to pass this in as an argument to _minimize_blob instead? That would help a lot for people with different computational resources, etc.

**Comment by mattwthompson** [comment]
Yeah, that makes sense: 6c181e5

I'm defaulting it to 2 since that makes the most sense for CI, a very weakly-held preference
