### ISSUE TITLE
[feat] Order everything by QCArchive ID?

### ISSUE THREAD

**Issue by lilyminium** [mattwthompson/ib#9]
MoleculeStore has a number of `get_x_by_y` methods, some of which order the output by QCArchive ID, some of which don't. For example, `get_[q/m]m_conformers_by_molecule_id` does order by QCArchive ID, but `get_qcarchive_ids_by_molecule_id` and `get_[q/m]m_energies_by_molecule_id` do not. In the benchmarks I run, I do see that the list of QCArchive IDs I get out of `get_qcarchive_ids_by_molecule_id` isn't necessarily in order, so it becomes much more difficult to cross-reference QCArchive IDs to geometries and so on when debugging or looking more closely at results.

Also, I'm not certain queries are guaranteed to be in a particular order -- which could be problematic for metrics such as ddEs that (as currently implemented) rely on the returned QM energies, MM energies, and QCA IDs to be in the same order. (That being said, in practice and having checked my own results they currently are, so I could be wrong here and this could be over-caution!)

**Comment by mattwthompson** [comment]
`get_qcarchive_ids_by_molecule_id` is now meant to sort by QCArchive ID (#11 / 0.0.0). There's a minimal unit test that shuffles the molecules before making a `MoleculeStore` and later checks that the getter returns them sorted.

> Also, I'm not certain queries are guaranteed to be in a particular order 

Is "order" here just by `qcarchive_id` or are there other sortings that would be useful?
